# Uncomment the next line to define a global platform for your project
 platform :ios, ‘9.0’


target 'RxSwiftTutorial' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftTutorial
    pod 'RxSwift'
    pod 'RxCocoa'

  target 'RxSwiftTutorialUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwiftTutorialTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
